<?php

declare(strict_types=1);

// Writes data/presentationforms.php: every Hebrew and Arabic presentation form (U+FB1D-U+FDFF and
// U+FE70-U+FEFC) with the ordinary letters it stands for, taken from the Unicode compatibility
// decompositions that the intl extension carries. Run it again after a Unicode update:
//
//     php tools/build-presentation-forms.php

if (!class_exists(Normalizer::class)) {
    fwrite(STDERR, "The intl extension is needed to build this table\n");
    exit(1);
}

$rows = [];
foreach ([[0xFB1D, 0xFDFF], [0xFE70, 0xFEFC]] as [$from, $to]) {
    for ($cp = $from; $cp <= $to; $cp++) {
        $char = mb_chr($cp, 'UTF-8');
        $plain = Normalizer::normalize($char, Normalizer::FORM_KC);
        if (!is_string($plain) || $plain === $char) {
            continue;
        }
        // The stand-alone vowel marks decompose to a space and the mark; the space is only there to carry it.
        $plain = ltrim($plain, ' ');
        $rows[] = sprintf('    "\\u{%04X}" => "%s",', $cp, implode('', array_map(
            static fn(string $c): string => sprintf('\\u{%04X}', mb_ord($c, 'UTF-8')),
            mb_str_split($plain, 1, 'UTF-8')
        )));
    }
}

$out = "<?php\n\n// Hebrew and Arabic presentation forms and the ordinary letters each one stands for.\n"
    . "// Generated by tools/build-presentation-forms.php from Unicode's compatibility decompositions. Do not edit by hand.\n\n"
    . "return [\n" . implode("\n", $rows) . "\n];\n";
file_put_contents(dirname(__DIR__) . '/data/presentationforms.php', $out);
printf("%d forms written\n", count($rows));
